-- Enable any necessary extensions
-- CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Drop tables if they exist (for easy re-runs/testing)
DROP TABLE IF EXISTS players;
DROP TABLE IF EXISTS team_seasons;
DROP TABLE IF EXISTS teams;

-- Teams Table (Unique teams across all seasons)
CREATE TABLE teams (
    id INTEGER PRIMARY KEY, -- API-Football team ID
    name TEXT NOT NULL,
    logo_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Team Seasons Table (Tracks which seasons a team participated in)
CREATE TABLE team_seasons (
    team_id INTEGER REFERENCES teams(id) ON DELETE CASCADE,
    season INTEGER NOT NULL, -- e.g., 2023 for 2023/2024
    PRIMARY KEY (team_id, season)
);

-- Players Table (Stores season-specific player profile & stats)
CREATE TABLE players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    api_id INTEGER NOT NULL, -- API-Football player ID
    team_id INTEGER REFERENCES teams(id) ON DELETE CASCADE,
    ucl_season INTEGER NOT NULL, -- Season year (e.g. 2023)
    name TEXT NOT NULL,
    rating INTEGER NOT NULL, -- Computed or curated overall rating
    position TEXT NOT NULL, -- Specific tactical position (e.g., ST, LW, RW, CAM, CM, CDM, CB, LB, RB, GK)
    generic_position TEXT NOT NULL, -- Generic position (Goalkeeper, Defender, Midfielder, Attacker)
    photo_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    -- Ensure we don't have duplicate records for the same player in the same team for the same season
    UNIQUE (api_id, team_id, ucl_season)
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_players_team_season ON players(team_id, ucl_season);
CREATE INDEX IF NOT EXISTS idx_players_rating ON players(rating);
CREATE INDEX IF NOT EXISTS idx_team_seasons_season ON team_seasons(season);
