export const styles = {
  appContainer: {
    width: '100%',
    maxWidth: '1280px',
    margin: '0 auto',
    padding: '20px',
    display: 'flex',
    flexDirection: 'column',
    minHeight: '100vh',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '30px',
    borderBottom: '1px solid var(--panel-border)',
    paddingBottom: '15px',
  },
  logoRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  logoStarball: {
    width: '40px',
    height: '40px',
    borderRadius: '50%',
    background: 'rgba(0, 240, 255, 0.1)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: '1.5px solid var(--cyan-glow)',
  },
  brandTitle: {
    fontSize: '1.4rem',
    fontWeight: '800',
    letterSpacing: '1px',
  },
  headerRight: {
    display: 'flex',
    alignItems: 'center',
  },
  liveBadge: {
    background: 'var(--danger)',
    color: '#ffffff',
    fontSize: '0.7rem',
    fontWeight: '800',
    padding: '3px 8px',
    borderRadius: '4px',
    letterSpacing: '0.5px',
  },
  setupCard: {
    maxWidth: '650px',
    margin: '40px auto',
    padding: '30px',
  },
  setupHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    borderBottom: '1px solid var(--panel-border)',
    paddingBottom: '15px',
    marginBottom: '25px',
  },
  setupForm: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  label: {
    fontSize: '0.8rem',
    fontWeight: '700',
    textTransform: 'uppercase',
    color: 'var(--text-muted)',
    letterSpacing: '0.5px',
  },
  input: {
    background: 'rgba(2, 11, 36, 0.6)',
    border: '1px solid var(--panel-border)',
    borderRadius: '8px',
    color: '#ffffff',
    padding: '12px 16px',
    fontSize: '1rem',
    outline: 'none',
    transition: 'all 0.2s ease',
  },
  radioGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
    gap: '12px',
  },
  radioButton: {
    background: 'rgba(255, 255, 255, 0.02)',
    borderWidth: '1.5px',
    borderStyle: 'solid',
    borderColor: 'var(--panel-border)',
    borderRadius: '8px',
    padding: '15px',
    cursor: 'pointer',
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    transition: 'all 0.2s ease',
  },
  radioButtonActive: {
    background: 'rgba(0, 240, 255, 0.05)',
    borderColor: 'var(--cyan-glow)',
    boxShadow: '0 0 15px rgba(0, 240, 255, 0.15)',
  },
  radioTitle: {
    fontSize: '0.95rem',
    fontWeight: '700',
  },
  radioDesc: {
    fontSize: '0.75rem',
    color: 'var(--text-muted)',
  },
  submitBtn: {
    marginTop: '10px',
    padding: '14px 28px',
  },
  draftWorkspace: {
    display: 'grid',
    gridTemplateColumns: '1.1fr 1.3fr',
    gap: '30px',
    alignItems: 'start',
  },
  pitchSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: '15px',
    alignItems: 'center',
  },
  squadSummaryPanel: {
    width: '100%',
    maxWidth: '620px',
    padding: '15px 20px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  squadTitle: {
    fontSize: '1.1rem',
    fontWeight: '700',
  },
  squadOvr: {
    fontSize: '0.85rem',
    color: 'var(--text-muted)',
  },
  proceedBtn: {
    width: '100%',
    maxWidth: '620px',
    padding: '14px 0',
  },
  selectorSection: {
    height: '100%',
  },
  setupWorkspace: {
    display: 'grid',
    gridTemplateColumns: '1.2fr 1fr',
    gap: '30px',
    alignItems: 'stretch',
    marginTop: '10px',
  },
  setupHeroPanel: {
    padding: '35px',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    gap: '30px',
    height: '100%',
  },
  heroBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    background: 'rgba(0, 240, 255, 0.08)',
    border: '1px solid rgba(0, 240, 255, 0.2)',
    color: 'var(--cyan-glow)',
    fontSize: '0.75rem',
    fontWeight: '700',
    padding: '5px 12px',
    borderRadius: '20px',
    alignSelf: 'start',
    letterSpacing: '0.5px',
    textTransform: 'uppercase',
  },
  heroMainTitle: {
    fontFamily: 'var(--font-title)',
    fontSize: '2.5rem',
    fontWeight: '900',
    lineHeight: '1.25',
    letterSpacing: '0.5px',
  },
  heroDescription: {
    color: 'var(--text-muted)',
    fontSize: '1rem',
    lineHeight: '1.6',
    marginTop: '10px',
  },
  featuresGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '15px',
    marginTop: '15px',
  },
  featureItem: {
    background: 'rgba(255, 255, 255, 0.01)',
    border: '1px solid rgba(255, 255, 255, 0.04)',
    borderRadius: '10px',
    padding: '15px',
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    transition: 'all 0.2s ease',
  },
  featureTitle: {
    fontSize: '0.85rem',
    fontWeight: '700',
    color: '#ffffff',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  featureDesc: {
    fontSize: '0.75rem',
    color: 'var(--text-muted)',
    lineHeight: '1.4',
  },
  quickStatsPanel: {
    background: 'linear-gradient(135deg, rgba(3, 16, 46, 0.9) 0%, rgba(2, 11, 36, 0.9) 100%)',
    border: '1px solid var(--panel-border)',
    borderRadius: '12px',
    padding: '15px 20px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  statBox: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '4px',
  },
  statValue: {
    fontSize: '1.3rem',
    fontWeight: '800',
    color: 'var(--cyan-glow)',
  },
  statLabel: {
    fontSize: '0.65rem',
    color: 'var(--text-muted)',
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
};
